package com.example.contesttracker

import retrofit2.http.GET
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory

interface ClistApiService {
    // Fetches the credential-free public feed generated by the GitHub Actions workflow.
    // No API key is stored in the app. The feed is refreshed every 15 minutes server-side.
    @GET("contests.json")
    suspend fun getUpcomingContests(): ContestResponse
}

object RetrofitClient {
    // Public GitHub Pages feed. No credentials required.
    // Populated by: .github/workflows/refresh-contests.yml
    const val BASE_URL = "https://dhruv-1309.github.io/Contestory/"

    val apiService: ClistApiService by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
            .create(ClistApiService::class.java)
    }
}
